apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-and-push-pipeline-run
spec:
  pipelineRef:
    name: build-and-push-pipeline
  serviceAccountName: default
  resources:
    - name: git-source
      resourceSpec:
        type: git
        params:
          - name: url
            value: "https://github.com/tkavya-05/DevopsProject/tree/main/my_docker_file"
  params:
    - name: gitrepo
      value:
        url: "https://github.com/tkavya-05/DevopsProject/tree/main/my_docker_file"  # Provide the Git repository URL here
    - name: context-dir
      value: "."
    - name: dockerfile
      value: "./Dockerfile"
    - name: docker-image
      value: "https://hub.docker.com/r/telukuntlakavya/my_docker_file"
  secrets:
    - name: regcred
