apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-and-push-task
spec:
  params:
    - name: context-dir
      description: The directory containing the Dockerfile and application code
      type: string
    - name: dockerfile
      description: The path to the Dockerfile
      type: string
    - name: docker-image
      description: The name of the Docker image to build
      type: string
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:latest
      env:
        - name: DOCKER_CONFIG
          value: /tekton/home/.docker/
      volumeMounts:
        - name: docker-config
          mountPath: /tekton/home/.docker/
      script: |
        #!/bin/sh
        echo "Building Docker image..."
        /kaniko/executor --context "${1}" --dockerfile "${2}" --destination "${3}"
      args:
        - "$(params.context-dir)"
        - "$(params.dockerfile)"
        - "$(params.docker-image)"
  volumes:
    - name: docker-config
      secret:
        secretName: regcred
