apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-and-push-pipeline-run
spec:
  pipelineRef:
    name: build-and-push-pipeline
  params:
    - name: gitrepo
      value:
        url: "https://github.com/YashPimple/Ruby_on_rails.git"
    - name: context-dir
      value: "Ruby_on_rails"
    - name: dockerfile
      value: "./Dockerfile"
    - name: docker-image
      value: "https://hub.docker.com/r/yashpimple22/railsapp:latest"
  serviceAccountName: default
