apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: git-clone-task-run
spec:
  taskRef:
    name: git-clone-task
  params:
    - name: gitrepo
      value:
        url:"https://github.com/tkavya-05/DevopsProject/tree/main/my_docker_file"
