apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-source
spec:
  type: git
  params:
    - name: revision
      value: main
    - name: url
      value: "https://github.com/tkavya-05/DevopsProject/tree/main/my_docker_file"
